
// This file is automatically created by parse_CAMR_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

[[maybe_unused]] static int state_nghost;
[[maybe_unused]] static int do_reflux;
[[maybe_unused]] static int refine_cut_cells;
[[maybe_unused]] static amrex::Real difmag;
[[maybe_unused]] static amrex::Real small;
[[maybe_unused]] static amrex::Real small_dens;
[[maybe_unused]] static amrex::Real small_temp;
[[maybe_unused]] static amrex::Real small_pres;
[[maybe_unused]] static int do_mol;
[[maybe_unused]] static int do_react;
[[maybe_unused]] static int add_ext_src;
[[maybe_unused]] static int add_grav_src;
[[maybe_unused]] static amrex::Real const_grav;
[[maybe_unused]] static int ppm_type;
[[maybe_unused]] static int ppm_trace_sources;
[[maybe_unused]] static int plm_iorder;
[[maybe_unused]] static int use_flattening;
[[maybe_unused]] static int dual_energy_update_E_from_e;
[[maybe_unused]] static amrex::Real dual_energy_eta1;
[[maybe_unused]] static amrex::Real dual_energy_eta2;
[[maybe_unused]] static int use_pslope;
[[maybe_unused]] static int allow_negative_energy;
[[maybe_unused]] static int allow_small_energy;
[[maybe_unused]] static int transverse_reset_density;
[[maybe_unused]] static int eb_weights_type;
[[maybe_unused]] static std::string redistribution_type;
[[maybe_unused]] static amrex::Real fixed_dt;
[[maybe_unused]] static amrex::Real initial_dt;
[[maybe_unused]] static amrex::Real dt_cutoff;
[[maybe_unused]] static amrex::Real max_dt;
[[maybe_unused]] static amrex::Real cfl;
[[maybe_unused]] static amrex::Real init_shrink;
[[maybe_unused]] static amrex::Real change_max;
[[maybe_unused]] static int bndry_func_thread_safe;
[[maybe_unused]] static int sum_interval;
[[maybe_unused]] static amrex::Real sum_per;
[[maybe_unused]] static std::string job_name;
[[maybe_unused]] static int write_eb;
