
// This file is automatically created by parse_CAMR_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

static int state_nghost;
static int do_reflux;
static int refine_cut_cells;
static amrex::Real difmag;
static amrex::Real small;
static amrex::Real small_dens;
static amrex::Real small_temp;
static amrex::Real small_pres;
static int do_mol;
static int do_react;
static int add_ext_src;
static int add_grav_src;
static amrex::Real const_grav;
static int ppm_type;
static int ppm_trace_sources;
static int plm_iorder;
static int use_flattening;
static int dual_energy_update_E_from_e;
static amrex::Real dual_energy_eta1;
static amrex::Real dual_energy_eta2;
static int use_pslope;
static int allow_negative_energy;
static int allow_small_energy;
static int transverse_reset_density;
static int eb_weights_type;
static std::string redistribution_type;
static amrex::Real fixed_dt;
static amrex::Real initial_dt;
static amrex::Real dt_cutoff;
static amrex::Real max_dt;
static amrex::Real cfl;
static amrex::Real init_shrink;
static amrex::Real change_max;
static int bndry_func_thread_safe;
static int sum_interval;
static amrex::Real sum_per;
static int hard_cfl_limit;
static std::string job_name;
static int write_eb;
